# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "34a42b96b110a1fbafa817f89660851a"
name = "Service Hub"
application_url = "https://symposium-billion-shapes-architects.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "ft-dev-discount-functions-app.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_products,write_discounts,write_cart_transforms"

[auth]
redirect_urls = [
  "https://symposium-billion-shapes-architects.trycloudflare.com/auth/callback",
  "https://symposium-billion-shapes-architects.trycloudflare.com/auth/shopify/callback",
  "https://symposium-billion-shapes-architects.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false
